snackbar : snackbar.c
	gcc snackbar.c -o snackbar

password : password.c
	gcc password.c -o password

rpc : rpc.c
	gcc rpc.c -o rpc

calculator : calculator.c
	gcc calculator.c -o calculator

fibonaci : fibonaci.c
	gcc fibonaci.c -o fibonaci

clean :
	rm snackbar password rpc fibonaci 2> /dev/null

