dynamic_snackbar : dynamic_snackbar.c
	gcc dynamic_snackbar.c -o dynamic_snackbar

repeat : repeat.c
	gcc repeat.c -o repeat

wordguess : wordguess.c
	gcc wordguess.c -o wordguess

fibonaci : fibonaci.c	
	gcc fibonaci.c -o fibonaci

all: dynamic_snackbar repeat wordguess
	

clean :
	rm wordguess repeat dynamic_snackbar fibonaci calculator 2> /dev/null

